//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitGo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<ClubInfo> ClubInfo { get; set; }
        public virtual DbSet<Coupon> Coupon { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseSched> CourseSched { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
